### ISSUE TITLE
android release crash

### ISSUE THREAD

**Issue by shiguo2021** [MarnoDev/AC-QRCode-RN#71]
2019-11-19 11:58:13.649 5170-5195/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: cn.sg.jxc, PID: 5170
    java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
        at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java:91)
        at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:63)
        at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:59)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:355)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:216)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:784)

**Comment by nikunjdhamat** [comment]
I got the issue, There is problem with scanBarStyle, just remove the scanBarStyle if you have set to QRScannerView.

**Comment by leecz** [comment]
在第二次打开扫码页面时会崩溃，比如a,b 两个页面，b页面为扫码页，第一次a跳b页面没问题，返回a，再从a跳到b，就会崩溃闪退。去掉 scanBarStyle 就正常了。

**Comment by leecz** [comment]
使用react native 0.62版本， react navigation v5。
